social media ticker v1
96boards-projects/social-ticker pull request #1
Opened 2018-11-05 14:17 UTC by ric96

2018-11-05 15:21 UTC, Mani-Sadhasivam requested changes
Please add description and _always_ sign off. This holds true for both PR and commits.

2018-11-05 15:21 UTC, Mani-Sadhasivam commented on README.md
> +| Sensor Mezzanine | MAX7219 LED Matrix |
table rendering here and below is not proper!

2018-11-05 15:21 UTC, Mani-Sadhasivam commented on README.md
> +- I use ISCP to program the SeeedStudio Mezzanine. You can follow [this guide](https://www.96boards.org/blog/arduino-ide-sensor-mezzanine/).
s/use ISCP/used ICSP programmer

2018-11-16 12:35 UTC, ric96 commented
@Mani-Sadhasivam can you take a look? I've updated as required.

2018-11-16 14:03 UTC, Mani-Sadhasivam approved these changes

2018-11-16 14:03 UTC, merged